import type { Metadata } from 'next';
import '../globals.css';
import { UiProvider } from '@/services/context';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale } from 'next-intl/server';

export const metadata: Metadata = {
  title: 'DashStack',
  description: 'Generated by create next app',
};

export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body className="bg-black">
        <UiProvider>
          <NextIntlClientProvider>{children}</NextIntlClientProvider>
        </UiProvider>
      </body>
    </html>
  );
}
