import type { Metadata } from 'next';
import '../globals.css';
import { UiProvider } from '@/services/context';

export const metadata: Metadata = {
  title: 'DashStack',
  description: 'Generated by create next app',
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black">
        <UiProvider>{children}</UiProvider>
      </body>
    </html>
  );
}
