import type { Metadata } from 'next';
import '../globals.css';
import { Layout } from 'antd';
import { Header, Sidebar } from '@/components/layouts';
import { Content } from 'antd/es/layout/layout';
import { UiProvider } from '@/services/context';

export const metadata: Metadata = {
  title: 'DashStack',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UiProvider>
          <Layout style={{ minHeight: '100vh' }}>
            <Sidebar />
            <Layout>
              <Header />
              <Content style={{ marginInline: '1rem' }}>{children}</Content>
            </Layout>
          </Layout>
        </UiProvider>
      </body>
    </html>
  );
}
