import './globals.css';
import { UiProvider } from '@/services/context';
import { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { Nunito_Sans } from 'next/font/google';
import { getLocale } from 'next-intl/server';

const Nunito = Nunito_Sans({
  subsets: ['latin'],
});
export const metadata: Metadata = {
  title: 'DashStack',
  description: 'Generated by create next app',
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const locale = await getLocale();
  const isRTL = locale === 'ar';

  return (
    <html lang={locale} dir={isRTL ? 'rtl' : 'ltr'} className={Nunito.className}>
      <body>
        <NextIntlClientProvider>
          <UiProvider locale={locale}>{children}</UiProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
