import './globals.css';
import { AuthProvider, UiProvider } from '@/services/context';
import { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { Nunito_Sans } from 'next/font/google';
import { getLocale } from 'next-intl/server';

const Nunito = Nunito_Sans({
  subsets: ['latin'],
});
export const metadata: Metadata = {
  title: 'DashStack',
  description: 'Generated by create next app',
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const locale = await getLocale();
  const isRTL = locale === 'ar';
  return (
    <html lang={locale} dir={isRTL ? 'rtl' : 'ltr'} className={Nunito.className}>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
                (function() {
                const lightTheme = {
                    primary: '#4880FF',
                    background: '#F5F6FA',
                    text: '#202224',
                    border: '#D5D5D5',
                    input: '#F5F6FA',
                    card: '#FFFFFF',
                    'auth-input': '#f1f4f9',
                    danger: '#EF3826',
                    success: '#00B69B',
                    warning: '#FFA756',
                    info: '#6226EF',
                  };
                
                const root = document.documentElement;
                Object.entries(lightTheme).forEach(([key, value]) => {
                  root.style.setProperty('--c-' + key, value);
                });
                
                // Add smooth transitions for theme changes
                root.style.setProperty('transition', 'background-color 0.2s ease, color 0.2s ease');
              })();
            `,
          }}
        />
      </head>
      <body>
        <NextIntlClientProvider>
          <UiProvider locale={locale}>{children}</UiProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
